//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevTools.Host.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class PluginsSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static PluginsSettings defaultInstance = ((PluginsSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new PluginsSettings())));
        
        public static PluginsSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\Bohdan\\Repos\\dev-tools\\src\\wpf\\DevTools.Host\\bin\\Debug\\net5.0-windows")]
        public string Catalog {
            get {
                return ((string)(this["Catalog"]));
            }
            set {
                this["Catalog"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("*.Plugin.dll")]
        public string SearchPattern {
            get {
                return ((string)(this["SearchPattern"]));
            }
        }
    }
}
